config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#index'
  resources :teams, only: [:index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
# frozen_string_literal: true

class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :team
  belongs_to :service
end

app/models/service.rb
# frozen_string_literal: true

class Service < ApplicationRecord
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end
end

app/controllers/teams_controller.rb
# frozen_string_literal: true

class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/teams_helper.rb
# frozen_string_literal: true

module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NicBLendz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
  </body>
    <% unless (controller_name == 'sessions' && action_name == 'new') || (controller_name == 'registrations' && action_name == 'new') || (controller_name == "registrations" && action_name == "edit") %>
      <%= render 'shared/footer' %>
    <% end %>
</html>

app/views/pages/index.html.erb
<div class="vido" data-controller="slowed-video">
  <%= video_tag "nicblendz.mp4", autoplay: true, loop: true, oncanplay: "this.muted=true", class: "vid", data: { slowed_video_target: "video" } %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="big-footer">
  <div>
    <strong class="footer">NicBlendz, Barber Shop</strong>
    <p class="footer">Schönebergerstr. 123 <br>12345 Berlin</p>
  </div>

  <div>
    <strong class="footer">opening days</strong>
    <p class="footer">Mon - closed <br>
        Tue. - Wed.  09:00 - 8:00 pm <br>
        Thurs. - Fri.  09:00 - 8:00 pm <br>
        Sat. - 09:00 -  8:00 pm
    </p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="nv-items">
  <% if user_signed_in? %>
    <%# <%= link_to "Home", root_path, class: "buttons"  %>
    <%= link_to root_path do %>
      <%= image_tag("nic.png", alt: "nic", class: "logo") %>
    <% end %>
    <%= link_to "Team", teams_path, class: "buttons"  %>
    <%= link_to "Profile", edit_registration_path(:user), class: "buttons"  %>
    <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "buttons"  %>
  <% else %>
    <%= link_to root_path do %>
      <%= image_tag("nic.png", alt: "nic", class: "logo") %>
    <% end %>
    <%= link_to "Team", teams_path, class: "buttons"  %>
    <%= link_to "Register",  new_registration_path(:user), class: "buttons"  %>
    <%= link_to "Login", new_user_session_path, class: "buttons"  %>
  <% end %>
</div>